export const menuItems = [
  {
    id: 1,
    icon: "home",
    label: "داشبورد من",
    path: "/dashboard",
    role: "All",
    children: [],
  },
  {
    id: 2,
    icon: "plus",
    label: "ثبت تخلف جدید",
    path: "/",
    role: "All",
    children: [
      {
        id: 21,
        icon: "downArrow",
        label: "ثبت تخلف جدید",
        path: "/",
        role: "All",
        children: [],
      },
      {
        id: 22,
        icon: "downArrow",
        label: "ثبت تخلف جدید",
        path: "/",
        role: "All",
        children: [],
      },
    ],
  },
  {
    id: 3,
    icon: "file",
    label: "پرونده تخلف",
    path: "/",
    role: "All",
    children: [],
  },
  {
    id: 4,
    icon: "decision",
    label: "تصمیم های در حال اجرا",
    path: "/",
    role: "All",
    children: [],
  },
  {
    id: 5,
    icon: "criminally",
    label: "بار مجرمانه",
    path: "/",
    role: "All",
    children: [],
    hasDivider: true
  },
    {
    id: 6,
    icon: "ding",
    label: "اطلاعیه ها",
    path: "/",
    role: "All",
    children: [],
  },

  {
    id: 7,
    icon: "massages",
    label: "پیام ها",
    path: "/",
    role: "All",
    children: [],
  },
  {
    id: 8,
    icon: "baseInfo",
    label: "اطلاعات پایه",
    path: "/dashboard/basic-Information",
    role: "All",
    children: [],
    hasDivider: true
  },
  {
    id: 9,
    icon: "persons",
    label: "مدیریت اشخاص",
    path: "/dashboard/person/person-list",
    role: "All",
    children: [],
  },
  {
    id: 10,
    icon: "access",
    label: "مدیریت کاربران و دسترسی ها",
    path: "",
    role: "All",
    children: [
        {
            id: 101,
            icon: "user",
            label: "کاربران",
            path: "/dashboard/user-management/users",
            role: "All",
            children: [],
          },
          {
            id: 102,
            icon: "groups",
            label: "واحد های سازمانی",
            path: "/dashboard/groups",
            role: "All",
            children: [],
          },
          {
            id: 103,
            icon: "positions",
            label: "نقش ها",
            path: "/dashboard/positions",
            role: "All",
            children: [],
          },
    ],
  },
  {
    id: 11,
    icon: "logs",
    label: "لاگ های سامانه",
    path: "/",
    role: "All",
    children: [],
  },
  {
    id: 12,
    icon: "report",
    label: "گزارش",
    path: "/",
    role: "All",
    children: [],
  },
//   {
//     id: 13,
//     icon: "report",
//     label: "داشبورد ادمین",
//     path: "/admin",
//     role: "Administrator",
//     children: [],
//   },
];
